name: fengyq
author: fengyq
basurl: /fengyq.github.io
description: theme for jekyll
github: http://www.github.com/fengyq
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: IMM@pku.edu.cn
location: Beijing, China
disqus: diqus-fengyq

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
