name: Ping's Lab
author: fengyq
basurl: /fengyq.github.io
github: http://www.github.com/fengyq
PKU: http://www.pku.edu.cn
CLS: http://www.cls.edu.cn/english/PrincipalInvestigator/pi/index1646.shtml
IMM: http://www.imm.pku.edu.cn/news.php?id=196
email: IMM@pku.edu.cn
location: Beijing
disqus: diqus-fengyq

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
