name: Ping's Lab
author: fengyq
basurl: /fengyq.github.io
description: Lab of Signal Transduction
github: http://www.github.com/fengyq
PKU: http://www.pku.edu.cn
CLS: http://www.cls.edu.cn
email: IMM@pku.edu.cn
location: Beijing, China
disqus: diqus-fengyq

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
